version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: task
      POSTGRES_USER: irina
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432